#!/bin/bash

[[ $basedir != /* ]] && basedir="$PWD/$basedir"
basedir="${basedir%/*}"
cd "$basedir"

if [ ! -d conf ]; then
  mkdir -p conf/state conf/profiles
  cat <<EOF > conf/profiles/default
---
:nick: cccb9example
:logfile: /dev/stdout
:servers:
  servername:
    :host: irc.server.org
    :channels:
    - ! '#somechannel'
:superuser_password: Set this to something. Really
EOF
fi

if [ ! -d logs ]; then
  mkdir -p logs
fi

profile="${1:-default}"
if [ "$RUBY" ]; then
  RUBY_BIN="$RUBY"
elif which ruby2.2 >/dev/null 2>&1; then
  RUBY_BIN="ruby2.2"
elif which ruby2.1 >/dev/null 2>&1; then
  RUBY_BIN="ruby2.1"
elif which ruby2.0 >/dev/null 2>&1; then
  RUBY_BIN="ruby2.0"
else
  RUBY_BIN="ruby"
fi
export RUBY_BIN
$RUBY_BIN -I "$basedir/lib" "$basedir/lib/cccb/init.rb" "$basedir" "$profile"
